name: Sync Rules to Splunk

# Bu hissə skriptin nə vaxt avtomatik işə düşəcəyini təyin edir
on:
  push:
    branches:
      - main  # main branch-inə hər kod push olunanda işə düşəcək
  schedule:
    - cron: '*/5 * * * *' # Həmçinin hər 5 dəqiqədən bir avtomatik yoxlayacaq

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # 1. GitHub-dakı kodları virtual maşına yükləyir
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Python mühitini qurur
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-python-version: '3.x'

    # 3. Lazım olan kitabxanaları yükləyir
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests urllib3

    # 4. Sənin yazdığın skripti təhlükəsiz tokenlə işlədir
    - name: Run Splunk Script
      env:
        # GitHub Secrets-ə əlavə etdiyimiz SPLUNK_TOKEN-i bura bağlayırıq
        SPLUNK_TOKEN: ${{ secrets.SPLUNK_TOKEN }} 
     - name: Run Splunk Script
        run: python siem-detection-as-code/splunk/deploy_splunk.py
